### ISSUE TITLE
Map mockup

### ISSUE THREAD

**Issue by ce-walalang** [WWCodeHackathon/phlib#3]
* color scheme
  * landscape
  * water
  * road
  * points of interest
  * transit
* icon svgs

**Comment by ce-manalang** [comment]
changed in console.cloud.google.com
<img width="1440" alt="Screenshot 2023-10-20 at 8 39 15 PM" src="https://github.com/WWCodeHackathon/phlib/assets/353784/ee5d5524-c789-4249-8332-205462bf629e">
